version: "3.9"

services:
  api:
    build:
      context: ../..
      dockerfile: emperor/Dockerfile
    image: emperator/api:dev
    env_file:
      - ../env/dev.env.example
    ports:
      - "8000:8000"
    command: [ "uvicorn", "emperator.api:app", "--host", "0.0.0.0", "--port", "8000" ]
