name: Emperator CI

on:
  push:
    paths:
      - 'emperator/**'
  pull_request:
    paths:
      - 'emperator/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run linters
        run: ruff check emperator/src
      - name: Type check
        run: mypy emperator/src
      - name: Run tests
        run: pytest emperator/tests
